farbe = input("Bitte Farbe eingeben: ")
plural_noun = input("Bitte ein Ding definieren: ")
promi = input("Bitte einen Promi benennen: ")
print("Rosen sind " + farbe)
print(plural_noun + " sind blau")
print("Ich liebe " + promi)